### PR TITLE
Migrate to dart 2

### PR DESCRIPTION
**Pull request by VerTiGoEtrex**
Move flutter_built_redux to support Dart 2 and a wider version of the built* generators.

This change removes support for Dart 1.

* Tests pass
* My app using flutter_built_redux functions fine with these changes

PTAL @davidmarne

### CODE REVIEW

**Comment by dougdonohoe** [comment]
We are trying to upgrade to Flutter 0.6.0 and are stuck on this dependency.  Is it possible to merge in this PR?  Thanks!

**Comment by davidmarne** [comment]
@dougdonohoe this has been published to pub
@VerTiGoEtrex thanks for taking the time to make these changes

**Comment by dougdonohoe** [comment]
Great thanks!  When will it show up here: https://pub.dartlang.org/packages/flutter_built_redux ?

**Comment by davidmarne** [comment]
lol @dougdonohoe my command to publish it was hung waiting for some user input so it didn't get pushed like i thought i did. should be good now

**Pull request merged**
